## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'mockexamples'

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_mockexamples' #to modify
description = 'Set of advanced Mock examples to test PyMoDAQ functionnalities'

author = 'Sebastien J. Weber'
author-email = 'sebastien.weber@cnrs.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.2.0']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
pid_models = true  # true if plugins contains pid models
h5exporters = true  # true if plugin contains custom h5 file exporters
scanners = true  # true if plugin contains custom scan layout (daq_scan extensions)
models = true

